server:
  # Google Cloud Run tells us where to listen using the PORT environment variable.
  # Our k8s deployments use the Spring Boot name, SERVER_PORT.
  # The following line allows either PORT or SERVER_PORT to specify the port the service listens on.
  # If neither is specified, the default port will be 8085. This is a good default for local development.
  # If both are specified (not recommended) SERVER_PORT will take precedence.
  port: ${PORT:8086}

idp:
  enabled: true
  base-url: http://localhost:8082
  authorize-url: ${idp.base-url}/oauth2/auth
  token-url: ${idp.base-url}/oauth2/token
  revoke-url: ${idp.base-url}/oauth2/revoke
  user-info-url: ${idp.base-url}/userinfo
  client-id: 812c1319-fef5-4aa6-9393-beb5ec8facdf
  client-secret: 0000-0000-0000-0000-0000

ic:
  enabled: true
  base-url: ${idp.base-url}
  client-id: ${idp.client-id}
  client-secret: ${idp.client-secret}

ddap:
  public-uri: http://localhost:8086
  enable-experimental: false
  default-realm: dnastack
  # Development key should not be deployed. There is an e2e test preventing this.
  signingKey: |
    VGhlcmUgb25jZSB3YXMgYSBsYW5ndWFnZSBjYWxsZWQgYmFzaApJdCdzIHNlbWFudGljcyB3ZXJlIG9mdGVuIHF1aXRlI
    HJhc2gKQnV0IGl0IHdvcmtlZCwgbW9yZSBvciBsZXNzCkV2ZW4gdGhvdWdoIGl0J3MgYSBtZXNzClNvIEkgZ3Vlc3MgaX
    Qgc3RheXMgb3V0IG9mIHRoZSB0cmFzaAo=
  cors:
    origins: "http://localhost:4200"
  cookies:
    # Default to false so cookies work on http://localhost
    # e2e tests will remind you to set this true in real deployments!
    secure: false
    encryptor:
      password: 'abcdefghijk'
      salt: '598953e322' # must be at least 8 char length and hexadecimal
  command-line-service:
    aud: ${ddap.public-uri}
    ttl: PT10M
    signingKey: ${ddap.signingKey}
  state-handler:
    aud: ${ddap.public-uri}
    ttl: PT10M
    signingKey: ${ddap.signingKey}
  wdl-validator:
    url: https://wdl-validator.staging.dnastack.com
    token: 1c0c52bedbc8c88bd998fa919243f32bcf5b201818288f112a477d118cc24d36

spring:
  cloud:
    gateway:
      routes:
        # NB: If you add a new route here,
        # you may also need to modify com.dnastack.ddapfrontend.route.Router#angluarRoutes
        # Important: Routes for the DAM are in com.dnastack.ddapfrontend.route.DamRouter
        #
        # Deprecated: use /proxy/** path for IC calls
        - predicates:
            - Path=/identity/**
          filters:
            - name: TimeoutAndRetry
              args:
                retries: 2
                minimumTimeout: 1000
                maximumTimeout: 20000
                timeoutExponentialScalingBase: 10
            - Logging
            - AddRequestParameter=clientId,${idp.client-id}
            - AddRequestParameter=clientSecret,${idp.client-secret}
            - RemoveRequestHeader=Authorization
            - SetBearerTokenFromCookie=IC,ACCESS
          uri: ${idp.base-url}
        - predicates:
            - Path=/proxy/**
          filters:
            - name: TimeoutAndRetry
              args:
                retries: 2
                minimumTimeout: 1000
                maximumTimeout: 20000
                timeoutExponentialScalingBase: 10
            - StripPrefix=1
            - Logging
            - AddRequestParameter=clientId,${idp.client-id}
            - AddRequestParameter=clientSecret,${idp.client-secret}
            - RemoveRequestHeader=Authorization
            - SetBearerTokenFromCookie=IC,ACCESS
          uri: ${idp.base-url}
logging:
  level:
    com:
      dnastack:
        ddap: DEBUG

---

spring:
  profiles: auth
  security:
    user:
      name: dev
      password: dev
